name: Build and Push to ACR

# This triggers the action whenever code is pushed to the 'main' branch
on:
  push:
    branches:
      - main

# Required for Workload Identity Federation (OIDC)
permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@v4

      - name: "Azure Login via OIDC"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Build and Push Docker Image"
        run: |
          az acr login --name iamsukheacr18
          # Build the image using the short commit SHA as a tag
          docker build -t iamsukheacr18-ahbfhyd4e2buaxf0.azurecr.io/flask-app:${{ github.sha }} .
          # Push the image to ACR
          docker push iamsukheacr18-ahbfhyd4e2buaxf0.azurecr.io/flask-app:${{ github.sha }}
